import { randomBytes, randomInt, createHash } from 'node:crypto';
import { uid, now } from './store.mjs';
export class AppError extends Error { constructor(message,status=400){super(message);this.status=status;} }
const need=(value,message,status=400)=>{if(!value)throw new AppError(message,status);return value;};
const text=(value,label,max=200)=>need(typeof value==='string'&&value.trim().length>0&&value.trim().length<=max,`${label} is required (maximum ${max} characters).`)&&value.trim();
const email=v=>{v=text(v,'Email').toLowerCase();need(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v),'Enter a valid email address.');return v;};
const phone=v=>{v=text(v,'Phone').replace(/[\s()-]/g,'');need(/^\+[1-9]\d{7,14}$/.test(v),'Include a valid country code, for example +233.');return v;};
const photo=v=>{if(!v)return '';need(typeof v==='string'&&v.length<=700000&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v),'Use a PNG, JPEG or WebP photo smaller than 500 KB.');return v;};
export const permissions={Owner:['review','ledger','reports','users','branding','directory','messages'], 'Check-in Officer':['desk','ledger','directory'], 'Registration Officer':['review','directory'], 'Communications Officer':['messages'], Viewer:['reports'], Parent:['parent']};
export const has=(u,p)=>Boolean(u&&u.status==='active'&&permissions[u.role]?.includes(p));
export function requirePermission(u,p){need(has(u,p),'You do not have permission to open this area.',403);}
export function createDomain(s){
  const tenant=t=>need(s.get('tenant',t,t),'Institution not found.',404);
  const get=(k,t,id)=>need(s.get(k,t,id),'Record not found.',404);
  const save=(k,t,v)=>s.put(k,t,v);
  const audit=(t,u,action,target)=>save('audit',t,{id:uid(),at:now(),actorId:u.id,actor:u.name,action,target});
  const child=(t,id)=>get('child',t,id);
  const own=(u,c)=>need(c.parentId===u.id,'Record not found.',404);
  const latest=(t,id)=>s.events(t).find(e=>e.childId===id);
  const decorate=(t,c)=>({...c,attendance:latest(t,c.id)?.type==='CHECK_IN'?'Checked in':latest(t,c.id)?'Checked out':'Not checked in',lastEvent:latest(t,c.id)});
  const eligible=c=>c.status==='approved'&&c.consent&&c.identity&&c.inviteAccepted;
  function validGrant(t,a){need(a&&!a.revoked&&!a.used&&Date.parse(a.startsAt)<=Date.now()&&Date.parse(a.endsAt)>Date.now(),'Code is invalid, expired, revoked or already used.',409);need(eligible(get('collector',t,a.collectorId)),'Collector is no longer eligible for pickup.',409);return a;}
  const authByCode=(t,code)=>s.list('authorisation',t).find(a=>a.code===String(code||'').toUpperCase().replace(/\s/g,''));
  const optional=(value,max=1000)=>String(value||'').trim().slice(0,max);
  function validateChild(c){const name=text(c.name,'Child name');need(/^\d{4}-\d{2}-\d{2}$/.test(c.dob||'')&&Number.isFinite(Date.parse(c.dob))&&new Date(c.dob).toISOString().slice(0,10)===c.dob&&c.dob<=now().slice(0,10)&&c.dob>='2000-01-01','Enter a valid date of birth (2000 or later, not in the future).');need(['Nursery','Kindergarten','Primary 1','Primary 2','Primary 3'].includes(c.group),'Choose a valid class.');need(c.careConsent===true||(!c.allergies&&!c.dietaryNeeds&&!c.medicalConditions&&!c.accessibilityNeeds&&!c.emergencyInstructions),'Care-information consent is required when care needs are supplied.');const care={allergies:optional(c.allergies),dietaryNeeds:optional(c.dietaryNeeds),medicalConditions:optional(c.medicalConditions),accessibilityNeeds:optional(c.accessibilityNeeds),emergencyInstructions:optional(c.emergencyInstructions),careConsent:Boolean(c.careConsent),careUpdatedAt:now()};const safetyNote=[care.allergies&&`Allergies: ${care.allergies}`,care.medicalConditions&&`Medical: ${care.medicalConditions}`,care.emergencyInstructions&&`Emergency: ${care.emergencyInstructions}`].filter(Boolean).join(' · ');return {name,dob:c.dob,group:c.group,...care,safetyNote,photo:photo(c.photo)};}
  return {
    tenant,
    createInstitution(b){const slug=text(b.slug,'Institution code',40).toLowerCase();need(/^[a-z0-9](?:[a-z0-9-]{1,38}[a-z0-9])$/.test(slug),'Use 3–40 lowercase letters, numbers or hyphens.');need(!['api','admin','app','www','support'].includes(slug),'Choose another institution code.',409);need(b.authority==='yes','Authority confirmation is required.');need(!s.get('tenant',slug,slug),'That institution code is already in use.',409);const ownerEmail=email(b.ownerEmail),ownerPhone=phone(b.ownerPhone);return s.transaction(()=>{save('tenant',slug,{id:slug,name:text(b.name,'Institution name',100),ministry:text(b.ministry,'Ministry name',100),accent:'forest',timezone:'Africa/Accra',createdAt:now(),status:'active'});save('user',slug,{id:uid(),name:text(b.ownerName,'Owner name'),email:ownerEmail,phone:ownerPhone,role:'Owner',status:'active',version:1});return {id:slug};});},
    session(t,token){const ss=s.get('session',t,token||'');if(!ss||ss.expiresAt<Date.now())return null;const u=s.get('user',t,ss.userId);return u?.status==='active'?u:null;},
    login(t,b){tenant(t);const address=email(b.email);const u=s.list('user',t).find(u=>u.email===address&&u.status==='active');need(u,'No active account matches this email. Ask the institution to approve or invite you.',403);const id=uid(),otp=String(randomInt(100000,1000000));save('challenge',t,{id,userId:u.id,hash:createHash('sha256').update(otp).digest('hex'),expiresAt:Date.now()+300000,attempts:0});save('outbox',t,{id:uid(),kind:'SIGN_IN_CODE',recipient:address,channel:'email',status:process.env.NODE_ENV==='production'?'awaiting_provider':'development',createdAt:now()});return {id,...(process.env.NODE_ENV!=='production'?{developmentCode:otp}:{})};},
    verifyLogin(t,b){const c=get('challenge',t,b.id);need(c.expiresAt>Date.now()&&c.attempts<5,'Code expired or too many attempts. Request another code.');c.attempts++;save('challenge',t,c);need(createHash('sha256').update(String(b.code)).digest('hex')===c.hash,'That code is incorrect.');const u=get('user',t,c.userId);need(u.status==='active','Account is not active.',403);s.delete('challenge',t,c.id);const token=randomBytes(32).toString('hex');save('session',t,{id:token,userId:u.id,expiresAt:Date.now()+8*3600000});return {token,user:u};},
    logout(t,token){s.delete('session',t,token);return {ok:true};},
    state(t,u){tenant(t);need(u,'Please sign in.',401);const parent=has(u,'parent'),directory=has(u,'directory'),messenger=has(u,'messages');const children=(parent?s.list('child',t).filter(c=>c.parentId===u.id):directory?s.list('child',t):[]).map(c=>decorate(t,c));const ids=new Set(children.map(c=>c.id));const families=s.list('family',t).filter(f=>parent?f.parentId===u.id:directory||messenger);const grants=parent?s.list('authorisation',t).filter(a=>a.parentId===u.id):[];return {user:u,permissions:permissions[u.role],tenant:tenant(t),children,families,collectors:s.list('collector',t).filter(c=>parent?c.parentId===u.id:directory).map(c=>{const {inviteToken,...safe}=c;return safe;}),authorisations:grants,events:(parent?s.events(t).filter(e=>ids.has(e.childId)):has(u,'ledger')?s.events(t):[]),applications:has(u,'review')?s.list('application',t):[],users:has(u,'users')?s.list('user',t):[],messages:s.list('message',t).filter(m=>parent?m.parentId===u.id:messenger),notifications:parent?s.list('notification',t).filter(n=>n.userId===u.id).reverse():[],announcements:messenger?s.list('announcement',t).reverse():[],deliveryStatus:has(u,'users')?{email:process.env.EMAIL_PROVIDER?'configured':'configuration_required',sms:process.env.SMS_PROVIDER?'configured':'configuration_required',inApp:'active'}:null,report:has(u,'reports')?{children:s.list('child',t).length,checkedIn:s.list('child',t).filter(c=>latest(t,c.id)?.type==='CHECK_IN').length,events:s.events(t).map(e=>({type:e.type,at:e.at})),pending:s.list('application',t).filter(a=>a.status==='pending').length,collectors:s.list('collector',t).filter(eligible).length}:null,audit:has(u,'users')?s.list('audit',t).slice(-20).reverse():[]};},
    register(t,b){tenant(t);const parent={name:text(b.parent?.name,'Parent name'),email:email(b.parent?.email),phone:phone(b.parent?.phone),relationship:text(b.parent?.relationship,'Relationship')};need(Array.isArray(b.children)&&b.children.length>0&&b.children.length<=10,'Add between one and ten children.');const children=b.children.map(validateChild);const requestKey=text(b.requestKey,'Submission reference');return s.transaction(()=>{const prior=s.list('application',t).find(a=>a.requestKey===requestKey);if(prior){need(prior.parent.email===parent.email,'Submission conflict.',409);return {id:prior.id,status:prior.status};}need(!s.list('user',t).some(u=>u.email===parent.email)&&!s.list('application',t).some(a=>a.parent?.email===parent.email&&a.status!=='rejected'),'This email already has a registration or account.',409);const a={id:uid(),requestKey,type:'family',parent,children,status:'pending',version:1,createdAt:now()};save('application',t,a);return {id:a.id,status:a.status};});},
    decide(t,u,id,b){requirePermission(u,'review');return s.transaction(()=>{const a=get('application',t,id);need(a.status==='pending'&&a.version===b.version,'This application changed. Reload before deciding.',409);need(['approved','rejected'].includes(b.decision),'Choose a decision.');if(b.decision==='rejected')text(b.reason,'Rejection reason',1000);if(a.type==='collector'&&b.decision==='approved'){const c=get('collector',t,a.collectorId);need(c.inviteAccepted&&c.consent,'Collector must first accept the invitation and consent.');need(b.identityConfirmed===true,'Confirm that identity was checked in person.');save('collector',t,{...c,status:'approved',identity:true});}if(a.type==='collector'&&b.decision==='rejected'){const c=get('collector',t,a.collectorId);save('collector',t,{...c,status:'rejected'});}if(a.type==='family'&&b.decision==='approved'){need(!s.list('user',t).some(u=>u.email===a.parent.email),'An account already uses this email.',409);const user={id:uid(),...a.parent,role:'Parent',status:'active',version:1};save('user',t,user);const family={id:uid(),parentId:user.id,name:a.parent.name+' family',status:'approved',relationship:a.parent.relationship};save('family',t,family);a.children.forEach(c=>save('child',t,{id:uid(),...c,parentId:user.id,familyId:family.id,status:'approved'}));}save('application',t,{...a,status:b.decision,reason:b.reason||'',version:a.version+1,decidedBy:u.name,decidedAt:now()});audit(t,u,b.decision,a.id);return {ok:true};});},
    invite(t,u,b){requirePermission(u,'parent');const c={id:uid(),parentId:u.id,name:text(b.name,'Collector name'),email:email(b.email),phone:phone(b.phone),relationship:text(b.relationship,'Relationship'),photo:photo(b.photo),status:'pending',consent:false,identity:false,inviteAccepted:false,inviteToken:randomBytes(24).toString('hex'),inviteExpiresAt:Date.now()+7*86400000};save('collector',t,c);save('application',t,{id:uid(),type:'collector',collectorId:c.id,name:c.name,status:'pending',version:1,createdAt:now()});return {id:c.id,inviteToken:c.inviteToken};},
    acceptInvite(t,b){const c=s.list('collector',t).find(c=>c.inviteToken===b.token);need(c&&c.inviteExpiresAt>Date.now()&&!c.inviteAccepted,'Invitation is invalid, expired or already accepted.');need(b.consent===true,'Consent is required.');save('collector',t,{...c,consent:true,inviteAccepted:true,acceptedAt:now()});return {ok:true};},
    authorise(t,u,b){requirePermission(u,'parent');const c=child(t,b.childId);own(u,c);const col=get('collector',t,b.collectorId);own(u,col);need(eligible(col),'Choose an approved, verified collector.');const start=Date.parse(b.startsAt),end=Date.parse(b.endsAt);need(Number.isFinite(start)&&Number.isFinite(end)&&end>Math.max(start,Date.now())&&end-start<=7*86400000,'Choose a valid period of up to seven days.');const a={id:uid(),parentId:u.id,childId:c.id,collectorId:col.id,startsAt:new Date(start).toISOString(),endsAt:new Date(end).toISOString(),code:'KL-'+randomBytes(5).toString('hex').toUpperCase(),note:String(b.note||'').slice(0,500),revoked:false,used:false,createdAt:now()};save('authorisation',t,a);return a;},
    revoke(t,u,id){requirePermission(u,'parent');const a=get('authorisation',t,id);own(u,a);save('authorisation',t,{...a,revoked:true});audit(t,u,'revoked',id);return {ok:true};},
    collectorCheck(t,b){tenant(t);validGrant(t,authByCode(t,b.code));return {valid:true,message:'This pickup code is active. Present it to the church team, who will verify identity and complete the handover.'};},
    checkin(t,u,b){requirePermission(u,'desk');return s.transaction(()=>{const c=child(t,b.childId);need(c.status==='approved','Registration must be approved.');const key=`${t}:${u.id}:in:${text(b.requestKey,'Request reference')}`;const prior=s.eventByKey(key);if(prior){need(prior.childId===c.id,'Request reference already used.',409);return prior;}need(latest(t,c.id)?.type!=='CHECK_IN','This child is already checked in.',409);const event=s.append(t,{id:uid(),requestKey:key,childId:c.id,type:'CHECK_IN',at:now(),actorId:u.id,staffName:u.name,notification:'not_connected'});return event;});},
    verifyPickup(t,u,b){requirePermission(u,'desk');const a=validGrant(t,authByCode(t,b.code));need(latest(t,a.childId)?.type==='CHECK_IN','This child is not currently checked in.',409);const v={id:uid(),authorisationId:a.id,staffId:u.id,expiresAt:Date.now()+5*60000};save('verification',t,v);return {id:v.id};},
    verification(t,u,id){requirePermission(u,'desk');const v=get('verification',t,id);need(v.staffId===u.id&&v.expiresAt>Date.now(),'Verification expired. Verify the code again.',409);const a=validGrant(t,get('authorisation',t,v.authorisationId));need(latest(t,a.childId)?.type==='CHECK_IN','Child already checked out.',409);const {inviteToken,...collector}=get('collector',t,a.collectorId);return {id:v.id,child:decorate(t,child(t,a.childId)),collector,endsAt:a.endsAt,expiresAt:v.expiresAt};},
    checkout(t,u,b){requirePermission(u,'desk');need(b.confirmed===true,'Physically verify the collector and child before confirming.');return s.transaction(()=>{const key=`${t}:${u.id}:out:${text(b.requestKey,'Request reference')}`;const prior=s.eventByKey(key);if(prior){need(prior.verificationId===b.verificationId,'Request reference already used.',409);return prior;}const v=this.verification(t,u,b.verificationId);const raw=get('verification',t,v.id);const a=get('authorisation',t,raw.authorisationId);const e=s.append(t,{id:uid(),requestKey:key,childId:v.child.id,type:'CHECK_OUT',at:now(),actorId:u.id,staffName:u.name,collectorId:v.collector.id,collectorName:v.collector.name,authorisationId:a.id,verificationId:v.id,notification:'not_connected'});save('authorisation',t,{...a,used:true});return e;});},
    operation(t,u,key){requirePermission(u,'desk');const e=s.eventByKey(`${t}:${u.id}:out:${key}`);return {event:e};},
    receipt(t,u,id){requirePermission(u,'desk');return need(s.events(t).find(e=>e.id===id),'Receipt not found.',404);},
    message(t,u,b){need(has(u,'parent')||has(u,'messages'),'Messaging is not available for this role.',403);const parentId=has(u,'parent')?u.id:text(b.parentId,'Family');need(get('user',t,parentId).role==='Parent','Choose a parent.');const requestKey=text(b.requestKey,'Message reference');const prior=s.list('message',t).find(m=>m.requestKey===requestKey&&m.actorId===u.id);if(prior)return prior;return save('message',t,{id:uid(),parentId,actorId:u.id,sender:u.name,body:text(b.body,'Message',2000),at:now(),requestKey});},
    announce(t,u,b){requirePermission(u,'messages');const title=text(b.title,'Title',120),body=text(b.body,'Announcement',2000),audience=['all','Nursery','Kindergarten','Primary 1','Primary 2','Primary 3'].includes(b.audience)?b.audience:'all';const requestKey=text(b.requestKey,'Announcement reference');const prior=s.list('announcement',t).find(a=>a.requestKey===requestKey);if(prior)return prior;const parents=s.list('user',t).filter(x=>x.role==='Parent'&&x.status==='active'&&(audience==='all'||s.list('child',t).some(c=>c.parentId===x.id&&c.group===audience)));const a=save('announcement',t,{id:uid(),title,body,audience,createdBy:u.id,sender:u.name,at:now(),requestKey,recipients:parents.length});parents.forEach(p=>save('notification',t,{id:uid(),userId:p.id,announcementId:a.id,title,body,sender:u.name,at:a.at,read:false,delivery:'in_app'}));audit(t,u,'sent announcement',a.id);return a;},
    readNotification(t,u,id){requirePermission(u,'parent');const n=get('notification',t,id);need(n.userId===u.id,'Record not found.',404);save('notification',t,{...n,read:true,readAt:now()});return {ok:true};},
    care(t,u,id,b){requirePermission(u,'parent');const c=child(t,id);own(u,c);const value=validateChild({...c,...b,name:c.name,dob:c.dob,group:c.group,photo:c.photo});save('child',t,{...c,...value});audit(t,u,'updated care information',id);return value;},
    branding(t,u,b){requirePermission(u,'branding');need(['forest','blue','plum'].includes(b.accent),'Choose an approved accent.');const value={...tenant(t),name:text(b.name,'Institution name',100),ministry:text(b.ministry,'Ministry name',100),accent:b.accent,logo:photo(b.logo)};save('tenant',t,value);audit(t,u,'updated branding',t);return value;},
    addUser(t,u,b){requirePermission(u,'users');const address=email(b.email);need(!s.list('user',t).some(x=>x.email===address),'This email already belongs to a user.',409);need(Object.keys(permissions).filter(r=>r!=='Parent').includes(b.role),'Choose a team role.');const value={id:uid(),name:text(b.name,'Name'),email:address,role:b.role,status:'invited',version:1};save('user',t,value);audit(t,u,'invited local user',value.id);return value;},
    updateUser(t,u,id,b){requirePermission(u,'users');const value=get('user',t,id);need(value.role!=='Parent','Parent access is managed through registrations.');need(b.version===value.version,'User changed. Reload and try again.',409);need(['active','suspended'].includes(b.status),'Choose a valid status.');need(id!==u.id||b.status==='active','You cannot suspend your own account.');if(value.role==='Owner'&&b.status!=='active')need(s.list('user',t).filter(x=>x.role==='Owner'&&x.status==='active').length>1,'Keep at least one active owner.');save('user',t,{...value,status:b.status,version:value.version+1});audit(t,u,'user '+b.status,id);return {ok:true};},
    profile(t,u,b){need(u,'Please sign in.',401);const v={...u,name:text(b.name,'Full name'),phone:phone(b.phone)};save('user',t,v);return v;}
  };
}
