import React from 'react';
import { ArrowRight, ShieldCheck, AlertCircle, Check, Inbox, LoaderCircle, Heart } from 'lucide-react';
import { base, navigate, time, date } from './api';
export function Link({to,children,className='',...props}){return <a href={base+to} className={className} {...props} onClick={e=>{if(!e.ctrlKey&&!e.metaKey&&!e.shiftKey){e.preventDefault();navigate(to);}}}>{children}</a>;}
export function Brand(){return <Link to="/" className="brand"><span className="brand-mark"><Heart size={22} fill="currentColor"/></span><span>Kiddie<span className="brand-light"> Log</span></span></Link>;}
export function Badge({children,tone}){const value=String(children||'');return <span className={'badge '+(tone||(/approved|active|Checked in|Recorded|verified|accepted/i.test(value)?'green':/rejected|suspended|revoked|expired/i.test(value)?'red':'amber'))}><i/>{children}</span>;}
export function Avatar({name='',photo,size='normal'}){return photo?<img className={'avatar '+size} src={photo} alt={name}/>:<span className={'avatar '+size+' hue-'+(name.charCodeAt(0)%4)} aria-hidden="true">{name.split(' ').map(v=>v[0]).slice(0,2).join('')}</span>;}
export function Button({children,variant='',busy=false,...props}){return <button {...props} disabled={busy||props.disabled} className={'button '+variant+' '+(props.className||'')}>{busy?<LoaderCircle size={17} className="spin"/>:null}{children}</button>;}
export function Field({label,hint,children,...props}){const fieldId=props.id||props.name;return <label className="field" htmlFor={fieldId}><span>{label}{props.required&&<small> *</small>}</span>{children||<input {...props} id={fieldId}/>} {hint&&<small className="muted">{hint}</small>}</label>;}
export function Notice({children,tone='info'}){return <div className={'notice '+tone} role={tone==='error'?'alert':'status'}>{tone==='error'?<AlertCircle size={20}/>:<ShieldCheck size={20}/>}<div>{children}</div></div>;}
export function Heading({eyebrow,title,description,action}){return <div className="page-heading"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description&&<p className="muted">{description}</p>}</div>{action}</div>;}
export function Empty({title='Nothing here yet',description='New activity will appear here.',action}){return <div className="empty"><Inbox size={32}/><h3>{title}</h3><p className="muted">{description}</p>{action}</div>;}
export function Loading(){return <div className="empty" role="status"><LoaderCircle className="spin"/><p>Loading your workspace…</p></div>;}
export function ChildCard({child,action}){return <article className="card child-card"><div className="row"><Avatar name={child.name} photo={child.photo} size="large"/><Badge>{child.attendance}</Badge></div><h3>{child.name}</h3><p className="muted">{child.group}</p><div className="card-foot"><span className="muted">{child.lastEvent?`${child.lastEvent.type==='CHECK_IN'?'Arrived':'Collected'} at ${time(child.lastEvent.at)}`:'Ready for a new day'}</span>{action||<Link to={'/parent/children/'+child.id} aria-label={'View '+child.name}><ArrowRight size={20}/></Link>}</div></article>;}
export function Success({title,description,children}){return <section className="card success"><div className="success-mark"><Check size={36}/></div><h1>{title}</h1><p className="muted">{description}</p>{children}</section>;}
export function EventTable({events,childrenList=[]}){if(!events.length)return <Empty title="No attendance records yet"/>;return <div className="table-wrap" tabIndex="0" aria-label="Attendance records"><table><thead><tr><th>Child</th><th>Event</th><th>Date & time</th><th>Recorded by</th><th>Collector</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td><strong>{childrenList.find(c=>c.id===e.childId)?.name||e.childId}</strong><small>{e.id.slice(0,8)}</small></td><td><Badge tone={e.type==='CHECK_IN'?'green':'blue'}>{e.type==='CHECK_IN'?'Check in':'Check out'}</Badge></td><td>{time(e.at)}<small>{date(e.at)}</small></td><td>{e.staffName}</td><td>{e.collectorName||'—'}</td></tr>)}</tbody></table></div>;}
export function PhotoField({value,onChange,label='Photo (optional)'}){const [error,setError]=React.useState('');return <div className="field"><span>{label}</span>{value&&<img className="photo-preview" src={value} alt="Upload preview"/>}<input type="file" accept="image/png,image/jpeg,image/webp" aria-label={label} onChange={e=>{const f=e.target.files[0];if(!f)return;if(f.size>500000||!['image/png','image/jpeg','image/webp'].includes(f.type)){setError('Choose a PNG, JPEG or WebP image under 500 KB.');return;}setError('');const r=new FileReader();r.onload=()=>onChange(r.result);r.readAsDataURL(f);}}/>{error&&<p role="alert">{error}</p>}{value&&<Button type="button" variant="text-button" onClick={()=>onChange('')}>Remove photo</Button>}</div>;}
